### ISSUE TITLE
프로젝트 이력 좌클릭 시 렌더링되지 않는 버그

### ISSUE THREAD

**Issue by c4854469c7f86af43b58246fb1782** [HeesuKim0203/MySite-Front#1]
안녕하세요 :)
MySite-Front 레포를 보고 포트폴리오 페이지를 방문했습니다. 중간에 사람모양의 아이콘을 클릭한 후 진행하신 프로젝트가 보고싶어서 좌클릭을 했지만 아무런 일도 일어나지 않았어요.  :(

우클릭하니 정상적으로 렌더링이 되었는데, 오타인가요?(master 브랜치의 `src/Routes/Home.js`)

저는 Brave browser v1.24.85를 MacOS Big Sur 11.3.1 환경에서 사용중입니다.

**Comment by HeesuKim0203** [comment]
넵 오타였습니다.
피드백 해주셔서 제가 오류를 수정할 수 있었습니다!
2021.05.20 20:10 이후로 수정 완료 되었습니다.
현재 AWS의 cloudFront로 배포 중이기 때문에 혹시 에러가 생기게 되면 새로고침 하면 해결됩니다!!

피드백 정말 감사드립니다.

**Comment by c4854469c7f86af43b58246fb1782** [comment]
왜 다시 열었어용??

**Comment by c4854469c7f86af43b58246fb1782** [comment]
ㅋㅋ 이슈 일하면 자주써요~

**Comment by HeesuKim0203** [comment]
빨리 공부하고 적응해야겠습니다!

**Comment by c4854469c7f86af43b58246fb1782** [comment]
뭐 하나 물어봐도 될까요?

2021년 5월 21일 (금) 오후 12:54, Heesu Kim ***@***.***>님이 작성:

**Comment by HeesuKim0203** [comment]
넵 물어보셔도 괜찮습니다!!

**Comment by c4854469c7f86af43b58246fb1782** [comment]
아뇨 별건아니고 코테 장고랑 자바스크립트중에 뭐 선택하셨나 궁금해서요

**Comment by HeesuKim0203** [comment]
저는 자바스크립트 선택했습니다.

**Comment by c4854469c7f86af43b58246fb1782** [comment]
오늘 고생하셨어요 :) 채점했습니당 어려웠나요 ㅠㅠ?

**Comment by HeesuKim0203** [comment]
음.. 이런 형식의 시험이 처음이여서 당황스러웠습니다. ㅠㅠ
먼가 제 실력을 100%발휘한 느낌이 아니라 조금 아쉽습니다. ㅠㅠ
혹시 점수는 언제쯤 나오나요??

**Comment by c4854469c7f86af43b58246fb1782** [comment]
채점은 다 했어용~ 연락드릴게요.
뭐가 제일 아쉬웠어요?

2021년 5월 30일 (일) 오후 4:59, Heesu Kim ***@***.***>님이 작성:

**Comment by HeesuKim0203** [comment]
음 일단 가장 아쉬운 건 차분하게 코드를 보고 천천히 제 페이스대로 했어야 했다입니다..
풀이에서 아쉬웠던 것은 dark 모드 적용에서 node를 가져오기 위해 쓴 getElementsByClassName가 반환값이 배열이라는 것을 알고 있었으면서 그것을 간과한 것, 리팩토링 문제에서 어떤 것부터 손대야할지 멘붕이 와서 손을 못댄 것이 있습니다.

**Comment by c4854469c7f86af43b58246fb1782** [comment]
너무 아쉬워하지마세요. 잘하셨어요.

다크모드는 localStorage물어보는 문제였구요, 리팩토링은 그냥 뭐 일본어로 된 폴더이름 바꾸는 정도면 거의 다
정답처리해드리고있어용

변수명도 일본어로 한거같은데.. 기억이안나네요 ㅋㅋ

희수씨 실력이면 다른 회사도 될것같은데 좋은 소식 있었나용?

2021년 5월 30일 (일) 오후 6:57, Heesu Kim ***@***.***>님이 작성:

**Comment by HeesuKim0203** [comment]
아직 좋은 소식 없습니다.
그래서 더 열심히 하고 있습니다!

**Comment by c4854469c7f86af43b58246fb1782** [comment]
네 좋은 소식 있을거에요. 참고로 리액트에서는 Node건드릴 땐, `querySelector`나 `getElementsByClassName`를 쓰지않아요....

**Comment by HeesuKim0203** [comment]
ref 사용해야 되는것 알고 있습니다!
급하니까 가장 편한걸 찾게 되더군요.. 
그럼 결과에 대한 소식 기다리고 있겠습니다!!
고생 하셨습니다!!

**Comment by TERADA-DANTE** [comment]
@HeesuKim0203 님이 1등이에용 ㅎ
희수씨 부탁이있는데,
Chung KyungSook 이분 깃헙 혹시 아세요?

**Comment by HeesuKim0203** [comment]
넵 알고있습니다.
어떤것 때문에 그러십니까?
 
-----Original Message-----

**Comment by c4854469c7f86af43b58246fb1782** [comment]
음 아 깃허브좀 보려고했는데, 찾은거같아서요:)
감사합니다

2021년 5월 31일 (월) 오후 2:54, Heesu Kim ***@***.***>님이 작성:

**Comment by HeesuKim0203** [comment]
​
넵 알겠습니다.
고생하십쇼!!

-----Original Message-----
