### ISSUE TITLE
도큐먼트 페이지 이미지 로딩 개선

### ISSUE THREAD

**Issue by hyunnnn98** [HeesuKim0203/MySite-Front#2]
https://blog.heesu99.site/document

**이미지 로딩 시 중간 부분이 짤리는 이슈**. ( 로딩속도 문제인듯? )

skeleton-content 도입은 어떤가요?

참고) https://www.npmjs.com/package/react-native-skeleton-content

**Comment by HeesuKim0203** [comment]
피드백 감사합니다. ^^
일단 방법을 모색한 뒤에 해결 후 이슈 닫도록 하겠습니다.

2021.06.03 이후로 해결 되었습니다.
AWS 서비스에는 추후에 파일을 업로드할 계획입니다.
