### ISSUE TITLE
게시물 정보 API 요청 시점

### ISSUE THREAD

**Issue by JeongJaeSoon** [HeesuKim0203/MySite-Front#3]
안녕하세요 지나가던 개발자입니다.

모든 페이지에서 새로고침을 하면 https://heesuserver.site/api/contents 를 통해,
게시물 정보를 가지고 오던데 의도하신건지 알 수 있을까요??

화면 로딩 속도 때문에 그렇게 하셨다면, 나중에 게시글 수가 많아졌을 때 어떻게 하실지도 궁금해요~!

**Comment by HeesuKim0203** [comment]
음.. 일단 최대한 빨리 다른 좋은 방법을 생각해서 고친 다음에 알려드리겠습니다!

cookie를 사용해서 리로딩 시 contents를 다시 받지 않게 수정 완료 했습니다!

**Comment by JeongJaeSoon** [comment]
오! 로딩 속도가 더 빨라진 느낌이 있네요!!! 너무 좋아요!!
덧붙여서 About 에 Website 에 주소를 추가할 수 있는데, 도메인도 있으니까 거기 추가하면 더 좋을거 같아요!!
